import { describe, expect, test } from "bun:test";
import { demoRuns } from "../src/data/demoRuns";
import { initialControl } from "../src/components/ControlView";
import { createInitialMockDatabase, runMockExperimentNow } from "../src/db/mockDb";
import { comparisonRuns } from "../src/components/CompareView";
import { dataOrigin } from "../src/components/WarningBanner";
import { isFabricatedRun, isWorseDelta, lowerIsBetter } from "../src/utils";

describe("metric polarity", () => {
  test("a rising error rate is worse, a rising AUC is better", () => {
    // The whole point of the shared rule: four metrics agree that up is bad, AUC disagrees.
    for (const metric of ["apcer", "bpcer", "acer", "hter"] as const) {
      expect(lowerIsBetter(metric)).toBe(true);
      expect(isWorseDelta(metric, 0.05)).toBe(true);
      expect(isWorseDelta(metric, -0.05)).toBe(false);
    }
    expect(lowerIsBetter("auc")).toBe(false);
    expect(isWorseDelta("auc", 0.05)).toBe(false);
    expect(isWorseDelta("auc", -0.05)).toBe(true);
  });

  test("no change is never reported as worse", () => {
    for (const metric of ["apcer", "bpcer", "acer", "hter", "auc"] as const) {
      expect(isWorseDelta(metric, 0)).toBe(false);
    }
  });
});

describe("fabricated rows", () => {
  test("a run generated by the control lab is marked as fabricated", () => {
    const state = createInitialMockDatabase(demoRuns, "export");
    const outcome = runMockExperimentNow(state, initialControl);
    const generated = outcome.item?.run;

    expect(generated).toBeDefined();
    // Its metrics come from mockDb's arithmetic, not from a measurement, so nothing may
    // present it as a result.
    expect(isFabricatedRun(generated!)).toBe(true);
    expect(generated!.researchClaimAllowed).toBe(false);
    expect(generated!.claimEligibility.allowed).toBe(false);
  });
});

describe("data origin", () => {
  test("bundled demo rows read as demo even before any export loads", () => {
    expect(dataOrigin("demo", demoRuns)).toBe("demo");
  });

  test("a real export on synthetic data is not called a real result", () => {
    // The synthetic sanity datasets export cleanly, so provenance alone would read "real".
    // research_claim_allowed is what separates a usable result from a pipeline demonstration.
    const exported = demoRuns.map((run) => ({
      ...run,
      demoOnly: false,
      researchClaimAllowed: false,
    }));
    expect(dataOrigin("export", exported)).toBe("export_synthetic");
  });

  test("an export whose rows allow claims reads as a real result", () => {
    const exported = demoRuns.map((run) => ({
      ...run,
      demoOnly: false,
      researchClaimAllowed: true,
    }));
    expect(dataOrigin("export", exported)).toBe("export_real");
  });

  test("one fabricated row downgrades a real export to mixed", () => {
    const exported = demoRuns.map((run) => ({
      ...run,
      demoOnly: false,
      researchClaimAllowed: true,
    }));
    const withMock = [...exported, { ...exported[0]!, runId: "mock_1", demoOnly: true }];
    expect(dataOrigin("export", withMock)).toBe("mixed");
  });

  test("an empty database does not claim to show exported results", () => {
    expect(dataOrigin("export", [])).toBe("demo");
  });
});

describe("comparison eligibility", () => {
  test("fabricated rows never enter a comparison, whatever the toggles say", () => {
    const state = createInitialMockDatabase(demoRuns, "export");
    const outcome = runMockExperimentNow(state, initialControl);
    const generated = outcome.item!.run;
    const pool = [...outcome.state.runs];

    // Both permissive switches on: smoke and risky rows are allowed back in, the mock row
    // still is not, because its numbers were never measured.
    const eligible = comparisonRuns(
      pool.filter((run) => run.experimentId === generated.experimentId),
      { includeSmoke: true, includeRisky: true },
    );
    expect(eligible.some((run) => run.runId === generated.runId)).toBe(false);
  });
});
