"""Frozen (resolved) specs: ``experiments/specs/<experiment.id>.resolved.yaml``.

Written only by ``scripts/validate_spec.py --freeze``; the launch gate requires the frozen
spec's ``science_hash`` to equal the spec about to run (``SPEC_FROZEN``).
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

import yaml

from pad_research.config.schema import ExperimentSpec, science_hash, spec_hash
from pad_research.protocols.hashing import protocol_hash


def frozen_path(experiment_id: str, specs_dir: Path) -> Path:
    return specs_dir / f"{experiment_id}.resolved.yaml"


def write_resolved_spec(spec: ExperimentSpec, specs_dir: Path) -> Path:
    specs_dir.mkdir(parents=True, exist_ok=True)
    path = frozen_path(spec.experiment.id, specs_dir)
    header = (
        "# GENERATED by scripts/validate_spec.py --freeze - do not edit by hand.\n"
        f"# science_hash: {science_hash(spec)}\n"
        f"# spec_hash: {spec_hash(spec)}\n"
        f"# protocol_hash: {protocol_hash(spec.protocol)}\n"
        f"# frozen_at: {_dt.datetime.now(tz=_dt.UTC).isoformat(timespec='seconds')}\n"
    )
    body = yaml.safe_dump(spec.model_dump(mode="json"), sort_keys=True, allow_unicode=True)
    path.write_text(header + body, encoding="utf-8")
    return path


def read_frozen_spec(experiment_id: str, specs_dir: Path) -> ExperimentSpec | None:
    path = frozen_path(experiment_id, specs_dir)
    if not path.is_file():
        return None
    return ExperimentSpec.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")))
